cabot-build:
  build: .

cabot-app:
  build: .
  links:
    - cabot-db
    - cabot-celerybroker
    - cabot-celery
  env_file: envs/cabot.env
  ports:
    - "8000:8000"
  command: gunicorn cabot.wsgi:application --config gunicorn.conf --log-level debug

cabot-celery:
  build: .
  links:
    - cabot-db
    - cabot-celerybroker
    - cabot-beat
  env_file: envs/cabot.env
  command: celery worker -A cabot --loglevel=INFO --concurrency=16 -Ofair

cabot-beat:
  build: .
  links:
    - cabot-db
    - cabot-celerybroker
  env_file: envs/cabot.env
  command: celery beat -A cabot --loglevel=INFO

cabot-db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker

cabot-celerybroker:
  image: redis:2.8

